/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVaultController,
  IVaultControllerInterface,
} from "../../../contracts/interfaces/IVaultController";

const _abi = [
  {
    inputs: [],
    name: "DepositForbidden",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "EmergencyWithdrawnFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "InitializedAlready",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "contract IStableCoin",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "decimals",
        type: "uint8",
      },
    ],
    name: "InvalidDecimals",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "beginTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
    ],
    name: "InvalidDepositTimeRange",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "contract IStableCoin",
        name: "asset",
        type: "address",
      },
    ],
    name: "InvalidStableCoin",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "beginTime",
        type: "uint256",
      },
    ],
    name: "InvalidWithdrawableTime",
    type: "error",
  },
  {
    inputs: [],
    name: "MoveForbidden",
    type: "error",
  },
  {
    inputs: [],
    name: "MovedAlready",
    type: "error",
  },
  {
    inputs: [],
    name: "NoReward",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "contract IStableCoin",
        name: "asset",
        type: "address",
      },
    ],
    name: "NonexistentStableCoin",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "beginTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentTime",
        type: "uint256",
      },
    ],
    name: "NotInDepositPeriod",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "beginTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentTime",
        type: "uint256",
      },
    ],
    name: "NotInWithdrawPeriod",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyFactory",
    type: "error",
  },
  {
    inputs: [],
    name: "TransferForbidden",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IStableCoin",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "decimals",
        type: "uint256",
      },
    ],
    name: "CoinAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "EmergencyWithdrawn",
    type: "event",
  },
] as const;

export class IVaultController__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultControllerInterface {
    return new Interface(_abi) as IVaultControllerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVaultController {
    return new Contract(address, _abi, runner) as unknown as IVaultController;
  }
}
