/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockSavingsVault__factory } from "./MockSavingsVault__factory";
export { StableCoin__factory } from "./StableCoin__factory";
