/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISavingsVault } from "./ISavingsVault";
export type { IStableCoin } from "./IStableCoin";
export type { IVaultController } from "./IVaultController";
